INFO:root:Executed R('load(\'../../instructor/assignments/hw5/hw5-tests2.rda\')')
INFO:root:Executed R('listLengths.r <- listLengths(test$listLengths)')
ERROR:root:(3 points) Checking R('all.equal(listLengths.r, sol$listLengths)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   target is NULL, current is numeric
ERROR:root:(1 points) Checking R('all.equal(length(listLengths.r), 5)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Mean absolute difference: 5
INFO:root:Executed R('standMatrixVariables.r1 <- abs(standMatrixVariables(test$standMatrixVariables.1))')
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "standMatrixVariables"

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "standMatrixVariables"

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "standMatrixVariables"

ERROR:root:(1 points) Checking R('all.equal(standMatrixVariables.r1, sol$standMatrixVariables.1, check.attributes=F, tolerence=1e-4)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(standMatrixVariables.r1, sol$standMatrixVariables.1,  : 
  object 'standMatrixVariables.r1' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(standMatrixVariables.r1, sol$standMatrixVariables.1,  : 
  object 'standMatrixVariables.r1' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(standMatrixVariables.r1, sol$standMatrixVariables.1,  : 
  object 'standMatrixVariables.r1' not found

INFO:root:Executed R('standMatrixVariables.r2 <- abs(standMatrixVariables(test$standMatrixVariables.2))')
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "standMatrixVariables"

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "standMatrixVariables"

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "standMatrixVariables"

ERROR:root:(3 points) Checking R('all.equal(standMatrixVariables.r2, sol$standMatrixVariables.2, check.attributes=F, tolerence=1e-4)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(standMatrixVariables.r2, sol$standMatrixVariables.2,  : 
  object 'standMatrixVariables.r2' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(standMatrixVariables.r2, sol$standMatrixVariables.2,  : 
  object 'standMatrixVariables.r2' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(standMatrixVariables.r2, sol$standMatrixVariables.2,  : 
  object 'standMatrixVariables.r2' not found

ERROR:root:(1 points) Checking R('all.equal(dim(standMatrixVariables.r2), c(3, 3))')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(dim(standMatrixVariables.r2), c(3, 3)) : 
  object 'standMatrixVariables.r2' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(dim(standMatrixVariables.r2), c(3, 3)) : 
  object 'standMatrixVariables.r2' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(dim(standMatrixVariables.r2), c(3, 3)) : 
  object 'standMatrixVariables.r2' not found

ERROR:root:(1 points) Checking R('all.equal(class(standMatrixVariables.r2), \'matrix\')')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(class(standMatrixVariables.r2), "matrix") : 
  object 'standMatrixVariables.r2' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(class(standMatrixVariables.r2), "matrix") : 
  object 'standMatrixVariables.r2' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(class(standMatrixVariables.r2), "matrix") : 
  object 'standMatrixVariables.r2' not found

INFO:root:Executed R('tGG.r1 <- testGroupsGestation(test$tGG.1, test$tGG.g1.1, test$tGG.g2.1, test.alternative="greater")')
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "testGroupsGestation"

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "testGroupsGestation"

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "testGroupsGestation"

ERROR:root:(1 points) Checking R('all.equal(tGG.r1$p.value, sol$testGroupGestation.1, check.attributes=F, tolerence=1e-4)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(tGG.r1$p.value, sol$testGroupGestation.1, check.attributes = F,  : 
  object 'tGG.r1' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(tGG.r1$p.value, sol$testGroupGestation.1, check.attributes = F,  : 
  object 'tGG.r1' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(tGG.r1$p.value, sol$testGroupGestation.1, check.attributes = F,  : 
  object 'tGG.r1' not found

INFO:root:Executed R('tGG.r2 <- testGroupsGestation(test$tGG.2, test$tGG.g1.2, test$tGG.g2.2, test.alternative=\'less\')')
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "testGroupsGestation"

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "testGroupsGestation"

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : 
  could not find function "testGroupsGestation"

ERROR:root:(3 points) Checking R('all.equal(tGG.r2$p.value, sol$testGroupGestation.2, check.attributes=F, tolerence=1e-4)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(tGG.r2$p.value, sol$testGroupGestation.2, check.attributes = F,  : 
  object 'tGG.r2' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(tGG.r2$p.value, sol$testGroupGestation.2, check.attributes = F,  : 
  object 'tGG.r2' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(tGG.r2$p.value, sol$testGroupGestation.2, check.attributes = F,  : 
  object 'tGG.r2' not found

ERROR:root:(2 points) Checking R('all.equal(smoking.test$p.value, sol$smoking.test, check.attributes=F, tolerence=1e-3)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(smoking.test$p.value, sol$smoking.test, check.attributes = F,  : 
  object 'smoking.test' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(smoking.test$p.value, sol$smoking.test, check.attributes = F,  : 
  object 'smoking.test' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(smoking.test$p.value, sol$smoking.test, check.attributes = F,  : 
  object 'smoking.test' not found

ERROR:root:(2 points) Checking R('all.equal(1-smoking.test$p.value, sol$smoking.test, check.attributes=F, tolerence=1e-3)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(1 - smoking.test$p.value, sol$smoking.test, check.attributes = F,  : 
  object 'smoking.test' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(1 - smoking.test$p.value, sol$smoking.test, check.attributes = F,  : 
  object 'smoking.test' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(1 - smoking.test$p.value, sol$smoking.test, check.attributes = F,  : 
  object 'smoking.test' not found

INFO:root:You got a 0 out of 16.
